# Generated by Django 6.0 on 2026-01-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название направления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='history/', verbose_name='Изображение')),
                ('years', models.CharField(max_length=100, verbose_name='Годы реализации')),
                ('location', models.CharField(max_length=200, verbose_name='География')),
            ],
            options={
                'verbose_name': 'Историческая линия',
                'verbose_name_plural': 'Исторические линии',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('main_content', models.TextField(default='', verbose_name='Основной текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('display_style', models.CharField(choices=[('grid', 'Сетка'), ('slider', 'Слайдер')], default='grid', max_length=10, verbose_name='Стиль отображения галереи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('role', models.CharField(max_length=200, verbose_name='Роль в проекте')),
                ('position', models.CharField(max_length=200, verbose_name='Должность/Место учебы')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на ВК')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.news')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фотографии новостей',
                'ordering': ['order'],
            },
        ),
    ]
